% The problem boils down to solving quadratic Diophantine equation 
% 2a^2 - 2a - n^2 + n = 0
% Solutions generated by Wolfram Alpha. 
% We take the upper right part of the hyperbole to ensure n > 0 and a > 0

m = 1;
while true
  tmp1 = (3 - 2 * sqrt(2)) ^ m;
  tmp2 = (3 + 2 * sqrt(2)) ^ m;
  a = (1/8) * ( 2*tmp1 + sqrt(2)*tmp1 + 2*tmp2 - sqrt(2)*tmp2 + 4);
  n = (1/4) * (-1*tmp1 - sqrt(2)*tmp1 - 1*tmp2 + sqrt(2)*tmp2 + 2);
  if n > 10^12
    break;
  else
    m = m + 1;
  end
end

fprintf('a = %f\n', a);
